apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: dev
spec:
  selector:
    matchLabels:
      app: my-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
        - image: iamraj007/mynginx:v2
          name: front-container-app
          ports:
            - containerPort: 80
              protocol: TCP
