apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev  
commonLabels:
  myenv: frontendapp-dev
resources:
 - ../../base/
 - deployment_app.yaml
images:
- name: iamraj007/mynginx
  newTag: v2
