apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:app-apparea, projects, get, apparea, allow
    p, role:app-apparea, repositories, *, apparea/*, allow
    p, role:app-apparea, applications, *, apparea/*, allow
    p, role:app-apparea, applications, sync, apparea/*, allow
    p, role:app-apparea, clusters, get, *, allow
    g, dev, role:app-apparea
    p, role:app-apparea-admin, projects, get, *, allow
    p, role:app-apparea-admin, repositories, *, *, allow
    p, role:app-apparea-admin, applications, get, *, allow
    p, role:app-apparea-admin, applications, create, *, allow
    p, role:app-apparea-admin, applications, sync, *, allow
    p, role:app-apparea-admin, applications, update, *, allow
    p, role:app-apparea-admin, clusters, get, *, allow
    p, role:app-apparea-admin, projects, get, ristricted/, deny
    g, devops, role:app-apparea-admin
