apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-deploy-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=iamraj007/mynginx
    argocd-image-updater.argoproj.io/site.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/site.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: argocd
    notifications.argoproj.io/subscribe.on-deleted.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-deployed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded.undefined: ArgoCD
    notifications.argoproj.io/subscribe.on-sync-failed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: ArgoCD     
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/ArgoCDGitOpsSetup.git
    targetRevision: HEAD
    path: apps/mynginx-webapp/overlays/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
