apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  accounts.dev: login
  accounts.dev.enabled: "true"
  accounts.devpower: login
  accounts.devpower.enabled: "true"
  accounts.devops: apiKey,login
  accounts.devops.enabled: "true"
