apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-setup-dev
  namespace: argocd
spec:
  project: proj-users
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    kustomize:
      namespace: *
    path: apps/user-setup/dev
    repoURL: https://github.com/iamraj007/ArgoCDGitOpsSetup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
