---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dumy1 
  namespace: kube-system
- kind: ServiceAccount
  name: dumy2
  namespace: kube-system
- kind: ServiceAccount
  name: usr3
  namespace: kube-system
- kind: ServiceAccount
  name: usr4
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-drainer-binding
subjects:
  - kind: ServiceAccount
    name: node-drainer
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-drainer
