---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-drainer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/eviction", "nodes"]
    verbs: ["get", "create", "list"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
