---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dumy1
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dumy2
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usr3
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usr4
  namespace: kube-system
