apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd 

commonLabels:
  myenv: my-web-frontendapp-devkustom

resources:
# - ns.yaml
 - ../../base/
 - appingress.yaml

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/mynginx
  newTag: v2

nameSuffix: -devenvapp
namePrefix: myweb-
